# Generated by Django 4.2.4 on 2024-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Grey', 'Grey'), ('Green', 'Green'), ('White', 'White')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=250, null=True),
        ),
    ]
