# Generated by Django 5.0.1 on 2024-02-08 05:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingApp', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=autoslug.fields.AutoSlugField(auto_created=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(auto_created=True, editable=False, populate_from='title', unique=True),
        ),
    ]
