# Generated by Django 5.0.1 on 2024-02-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingApp', '0006_alter_categories_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='PRODUCT_PIC/'),
        ),
    ]
