# Generated by Django 5.0.1 on 2024-03-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('sale_offer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
