# Generated by Django 5.0.1 on 2024-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderbanner',
            name='sale_offer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
