# Generated by Django 5.0.1 on 2024-03-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing_Accounts', '0002_alter_sliderbanner_sale_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='hotdeal/')),
                ('is_hot_deal', models.BooleanField(default=False)),
            ],
        ),
    ]
