# Generated by Django 5.0.1 on 2024-03-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing_Accounts', '0004_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotdeal',
        ),
    ]
